name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Set up SSH Agent and Add Key
        id: ssh-setup
        run: |
          echo "${{ secrets.DROPLET_SSH_KEY }}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          eval $(ssh-agent -s)
          ssh-add /tmp/ssh_key <<< "${{ secrets.SSH_PASSPHRASE }}"

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd /root/school-management/backend  # Adjust path as necessary
            git pull origin main
            npm install --development
            npm run dev
            # Optionally, restart your application using PM2:
            # pm2 restart <your_app_name>
